version: '3'

services:
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=example
    ports:
      - "33306:3306"

  app:
    build: .
    command: rails server -p 3000 -b '0.0.0.0'
    depends_on:
      - mysql
    links:
      - mysql
    volumes:
      - .:/project
    ports:
      - "3000:3000"
